"""IB2d example 2 — "Hoover Jellyfish" (Example_Jellyfish_Swimming) in AFSI.

The jellyfish locomotion model of Hoover & Miller 2015 ("A numerical study of
the benefits of driving jellyfish bells at their natural frequency",
J. Theor. Biol. 374: 13-25) as implemented in IB2d by N. Battista.  A 2-D bell
cross-section (truncated ellipse, arms hanging down) is immersed in a
periodic box of viscous fluid and driven by muscle springs between the arm
tips; the bell contracts, jets the fluid down and swims up.

Ingredients (all read from the IB2d input files, see ``make_jelly.py``):

* **springs** along the bell outline (kappa_spring = 1e7),
* **muscles**: npts_musc springs between the two arm tips (F = 1e5) whose
  resting length is re-set *every step* to ``|cos(freq*pi*t)|`` with freq = 2
  (IB2d's ``update_Springs.m``: L = |cos(2 pi t)|, one contraction every
  0.5 s) -- the swimming drive,
* **non-invariant beams** along the outline (kappa_beam = 2.5e5, reference
  second differences stored at t = 0),
* a line of **flow blocker target points** along the top edge (k = 2.5e6),
  tethered to their initial positions.

Fluid / coupling: identical pipeline to demo_444's rk2 path -- periodic Q2/Q1
Taylor-Hood, Peskin (2002) two-stage scheme (``PeskinRK2Solver``), Peskin
4-point kernel, Lagrangian weight ds = min(Lx/2Nx, Ly/2Ny), ``IBMesh(order=1)``
so the mesh vertices are IB2d's Eulerian grid.

The reduced case shipped here (input files in ``ib2d_input/``) scales the
original example (Nx x Ny = 192 x 640, dt = 1e-5, T = 5 s) by an exact 4x
coarser grid (48 x 160, ds = 1/32 instead of 1/128, dt = 4e-5), regenerated
with ``make_jelly.py`` so that IB2d's own conventions (kspring/ds, kbeam/ds^3,
ds = dx/2, muscle count floor(npts_wing/4)) hold at the coarser resolution.
Nothing outside this folder is needed: no IB2d checkout, no MATLAB/Octave.
The reference solution is produced in pure Python by ``run_reference.py``
(pyIB2d); for the original resolution regenerate the geometry, e.g.::

    python make_jelly.py /tmp/jelly_full 640 1e-5 5.0 5000
    IB2D_EXAMPLE=/tmp/jelly_full python main.py

Run::

    conda activate afsi-dolfinx
    python main.py                    # reduced case (T = 1 s), gamma = 100
    TFINAL=0.002 python main.py       # smoke test
    UPDATE_SPRINGS=0 python main.py   # passive bell (no muscle drive)
    GRAD_DIV=0 python main.py         # plain projection (no stabilisation)

``GRAD_DIV`` (default **100**, as in demo_444): the grad-div term suppresses the
spurious divergence of the coarse P2/P1 projection, which otherwise weakens the
jet -- over the first pulse gamma = 0 lags the IB2d reference by up to ~0.03 in
the bell centre of mass, gamma = 100 by ~0.01 (see readme).

Output (``OUTPUT_PATH``, default ``./plot``): XDMF fields +
``afsi_result_g<GRAD_DIV>.npz`` (t, X markers, u/p on the IB2d grid, bell com
and apex) -- same layout as the other IB2d demos.
"""
import os
import time

import numpy as np
from mpi4py import MPI
from petsc4py import PETSc

import basix.ufl
import dolfinx
import ufl
from dolfinx import fem
from dolfinx.fem.petsc import assemble_vector, create_vector
from dolfinx.mesh import CellType, GhostMode

from afsic import IBMesh, IBInterpolation
from afsic.euler.PeskinRK2Solver import PeskinRK2Solver

import ib2d_io

_here = os.path.dirname(os.path.abspath(__file__))
_repo = os.path.abspath(os.path.join(_here, *[".."] * 4))
# default: the reduced-resolution input generated by make_jelly.py
IB2D_EXAMPLE = os.environ.get("IB2D_EXAMPLE", os.path.join(_here, "ib2d_input"))

comm = MPI.COMM_WORLD
assert comm.size == 1, "this demo is serial (IB coupling of afsic gathers on rank 0)"

# ---------------------------------------------------------------------------
# Parameters: read from the IB2d example, optionally overridden
# ---------------------------------------------------------------------------
ex = ib2d_io.load_example(IB2D_EXAMPLE)
P = ex["params"]
rho, mu = float(P["rho"]), float(P["mu"])
Lx, Ly = float(P["Lx"]), float(P["Ly"])
Nx = int(os.environ.get("NX", P["Nx"]))
Ny = int(os.environ.get("NY", round(Nx * Ly / Lx)))
dt = float(os.environ.get("DT", P["dt"]))
T = float(os.environ.get("TFINAL", P["Tfinal"]))
print_dump = int(os.environ.get("PRINT_DUMP", P["print_dump"]))
assert Nx % 2 == 0 and Ny % 2 == 0, "Nx, Ny must be even (as in IB2d)"
num_steps = int(round(T / dt))
out_dir = os.environ.get("OUTPUT_PATH", os.path.join(_here, "plot"))
os.makedirs(out_dir, exist_ok=True)

GRAD_DIV = float(os.environ.get("GRAD_DIV", "100"))
MUSCLE_FREQ = float(os.environ.get("MUSCLE_FREQ", "2.0"))   # Hz, as update_Springs.m
UPDATE_SPRINGS = os.environ.get("UPDATE_SPRINGS", "1").lower() not in ("0", "", "false", "no")

X_ib2d = ex["X"]                              # (Nb, 2) IB2d ordering
Nb = X_ib2d.shape[0]
conn, k_spring, L0_spring, alpha = ex["springs"]
assert np.all(alpha == 1.0), "only linear IB2d springs are ported"
tgt_ids, tgt_k = ex.get("targets", (np.zeros(0, np.int64), np.zeros(0)))
bm = ex["beams"]
# the bell outline is chained by the FIRST (n_bell - 1) springs; the muscles
# are the LAST rows of the .spring file (Make_Jelly_Geometry.m order);
# the blockers are the target points (all of them).
n_bell = Nb - len(tgt_ids)
n_spring = len(conn)
# muscles: the springs with the contraction stiffness (written last by
# make_jelly.py); detect by stiffness so that it scales with the resolution
F_CONTRACTION = float(os.environ.get("F_CONTRACTION", "1e5"))
muscle_row = np.isclose(k_spring, F_CONTRACTION)
n_musc = int(muscle_row.sum())
assert n_musc > 0, "no muscle springs found (k == F_CONTRACTION)"
assert muscle_row[n_spring - n_musc:].all(), \
    "muscle springs must be the last rows of the .spring file"
# IB2d's Lagrangian weight (IBM_Driver.m: ds = min(Lx/(2Nx), Ly/(2Ny)))
ds_ib2d = min(Lx / (2 * Nx), Ly / (2 * Ny))
if comm.rank == 0:
    print(f"IB2d example : {IB2D_EXAMPLE}")
    print(f"rho={rho} mu={mu} box={Lx}x{Ly} grid={Nx}x{Ny} dt={dt} T={T} "
          f"steps={num_steps} ds={ds_ib2d}")
    print(f"structure    : {Nb} markers = {n_bell} bell + {len(tgt_ids)} blockers, "
          f"{n_spring} springs ({n_musc} muscles, f={MUSCLE_FREQ} Hz, "
          f"update={UPDATE_SPRINGS}), {len(bm['p1'])} beams")

# ---------------------------------------------------------------------------
# Fluid: periodic Taylor–Hood, Peskin two-stage scheme (as in demo_444)
# ---------------------------------------------------------------------------
mesh = dolfinx.mesh.create_rectangle(
    comm, ((0.0, 0.0), (Lx, Ly)), (Nx, Ny),
    cell_type=CellType.quadrilateral, ghost_mode=GhostMode.shared_facet)
solver = PeskinRK2Solver(mesh, (0.0, Lx, 0.0, Ly), dt, rho, mu, grad_div=GRAD_DIV)
Vc = solver.V

ibmesh = IBMesh(0.0, Lx, 0.0, Ly, Nx, Ny, 1)   # order 1: vertices = IB2d grid
V_ib = fem.functionspace(mesh, basix.ufl.element("Lagrange", "quadrilateral", 1,
                                                 shape=(2,)))
u_ib, f_ib = fem.Function(V_ib), fem.Function(V_ib)
coords_bg = fem.Function(V_ib)
coords_bg.interpolate(lambda x: np.array([x[0], x[1]]))
ibmesh.build_map(coords_bg._cpp_object)
ib = IBInterpolation(ibmesh)


def ib_velocity(u):
    """Eulerian velocity on the IB (vertex) grid."""
    u_ib.interpolate(u)
    return u_ib

# ---------------------------------------------------------------------------
# Structure: 1-D FE graph whose cells are the IB2d springs
# ---------------------------------------------------------------------------
# The blockers are isolated target points in IB2d; dolfinx drops geometry
# points not referenced by any cell, so a zero-stiffness chain over the
# blockers carries their dofs (it contributes nothing to any force).
if len(tgt_ids):
    blk = np.sort(tgt_ids)
    dummy = np.column_stack([blk[:-1], blk[1:]]).astype(np.int64)
else:
    dummy = np.zeros((0, 2), np.int64)
cells_all = np.vstack([conn, dummy]).astype(np.int64)
coord_el = basix.ufl.element("Lagrange", "interval", 1, shape=(2,))
structure = dolfinx.mesh.create_mesh(comm, cells_all, coord_el, X_ib2d)
Vs = fem.functionspace(structure, coord_el)
assert Vs.dofmap.index_map.size_local == Nb, \
    "the structure FE mesh must have one dof per IB2d marker"

DG0 = fem.functionspace(structure, ("DG", 0))
orig = structure.topology.original_cell_index
k_all = np.concatenate([k_spring, np.zeros(len(dummy))])
L_all = np.concatenate([L0_spring,
                        np.sqrt(((X_ib2d[dummy[:, 1]] - X_ib2d[dummy[:, 0]]) ** 2)
                                .sum(axis=1)) if len(dummy) else np.zeros(0)])
k_fn, L_fn = fem.Function(DG0), fem.Function(DG0)
k_fn.x.array[:] = k_all[orig]
L_fn.x.array[:] = L_all[orig]
muscle_cell = np.concatenate([muscle_row, np.zeros(len(dummy), bool)])[orig]

X = fem.Function(Vs, name="position")          # current configuration X(t)
X.interpolate(lambda x: np.array([x[0], x[1]]))
X_h = fem.Function(Vs, name="position_half")   # force configuration X^{n+1/2}
X_h.x.array[:] = X.x.array
U_s = fem.Function(Vs, name="velocity")
F_s = fem.Function(Vs, name="force")

# map FE dof -> IB2d point index (and back) by coordinate matching
dof_rows = Vs.tabulate_dof_coordinates()[:, :2]
dof_of_ib2d = np.array([int(np.argmin(np.linalg.norm(dof_rows - p, axis=1)))
                        for p in X_ib2d])
assert len(np.unique(dof_of_ib2d)) == Nb, "dof matching is not injective"
assert np.allclose(dof_rows[dof_of_ib2d], X_ib2d, atol=1e-12), \
    "dof coordinates do not recover the IB2d marker list"

# spring energy (exact for P1): E = sum_e 0.5 k/h0 (h0 |X_s| - L)^2 ds
h0 = ufl.CellVolume(structure)
gX = ufl.grad(X_h)
dXs = ufl.TestFunction(Vs)
dx_s = ufl.Measure("dx", domain=structure, metadata={"quadrature_degree": 2})
stretch = h0 * ufl.sqrt(ufl.inner(gX, gX) + 1e-30)
energy = 0.5 * k_fn / h0 * (stretch - L_fn) ** 2 * dx_s
force_form = fem.form(-ufl.derivative(energy, X_h, dXs))
F_vec = create_vector(Vs)


def spring_forces():
    """Nodal spring forces F_k at the configuration X_h (raw IB2d units)."""
    with F_vec.localForm() as loc:
        loc.set(0.0)
    assemble_vector(F_vec, force_form)
    F_vec.ghostUpdate(addv=PETSc.InsertMode.ADD, mode=PETSc.ScatterMode.REVERSE)
    F_s.x.petsc_vec.array[:] = F_vec.array_r
    F_s.x.scatter_forward()


def marker_array(fn):
    """Function on the structure space in IB2d marker order."""
    return fn.x.array.reshape(-1, 2)[dof_of_ib2d]


# ---------------------------------------------------------------------------
# Beam and target forces (IB2d formulas, evaluated at X_h)
# ---------------------------------------------------------------------------
bm_p1, bm_p2, bm_p3 = bm["p1"], bm["p2"], bm["p3"]
bm_k, bm_C = bm["kb"], bm["C"]
tgt_anchor = X_ib2d[tgt_ids].copy()


def extra_forces(Xm, Fm):
    """Beam + target force densities at marker positions Xm, added to Fm."""
    if len(bm_p1):
        r = (Xm[bm_p1] + Xm[bm_p3] - 2.0 * Xm[bm_p2]) - bm_C      # (nb, 2)
        np.add.at(Fm, bm_p2, 2.0 * bm_k[:, None] * r)
        np.add.at(Fm, bm_p1, -bm_k[:, None] * r)
        np.add.at(Fm, bm_p3, -bm_k[:, None] * r)
    if len(tgt_ids):
        d = tgt_anchor - Xm[tgt_ids]
        d -= np.round(d / np.array([Lx, Ly])) * np.array([Lx, Ly])   # min. image
        np.add.at(Fm, tgt_ids, tgt_k[:, None] * d)


def update_muscles(t):
    """IB2d update_Springs.m: muscle resting lengths -> |cos(freq * pi * t)|.

    (``freq = 2`` gives L = |cos(2 pi t)|: two contractions per second, i.e.
    one pulse every 0.5 s -- exactly the reference's ``abs(cos(freq*
    current_time*pi))``.)
    """
    L_fn.x.array[:] = np.where(muscle_cell,
                               np.abs(np.cos(np.pi * MUSCLE_FREQ * t)),
                               L_all[orig])


def spread_forces_at_half():
    """Total Lagrangian force at X_h (springs + beams + targets) x ds."""
    spring_forces()
    if len(bm_p1) or len(tgt_ids):
        Fm = np.zeros((Nb, 2))
        extra_forces(marker_array(X_h), Fm)
        Fdof = np.empty_like(Fm)
        Fdof[dof_of_ib2d] = Fm
        F_s.x.array[:] += Fdof.ravel()
    F_s.x.array[:] *= ds_ib2d
    ib.evaluate_current_points(X_h._cpp_object)
    ib.solid_to_fluid(f_ib._cpp_object, F_s._cpp_object)
    solver.periodic_fold(f_ib)
    if f_ib is not solver.f:
        solver.f.interpolate(f_ib)


# sanity check of the force machinery at a perturbed configuration (the
# initial state is stress-free by construction, so t = 0 is a trivial check)
rng = np.random.default_rng(0)
Xp = X_ib2d + 1e-3 * rng.standard_normal(X_ib2d.shape)
Xp_dof = np.empty_like(Xp)
Xp_dof[dof_of_ib2d] = Xp
X_h.x.array[:] = Xp_dof.ravel()
X_h.x.scatter_forward()
spring_forces()
Fm = np.zeros((Nb, 2))
extra_forces(Xp, Fm)
Fs_np = np.zeros((Nb, 2))
for (a, b), kk, LL in zip(conn, k_spring, L0_spring):
    d = Xp[b] - Xp[a]
    nd = np.sqrt((d ** 2).sum())
    f = kk * (nd - LL) * d / nd
    Fs_np[a] += f
    Fs_np[b] -= f
F_tot = Fs_np + Fm
# the FE side carries the springs only; the beams/targets are numpy-only
err = np.abs(marker_array(F_s) - Fs_np).max() / np.abs(Fs_np).max()
if comm.rank == 0:
    print(f"perturbed-config spring check vs IB2d formula: rel. max err = "
          f"{err:.2e} (scale {np.abs(Fs_np).max():.3g}, "
          f"beam/target scale {np.abs(Fm).max():.3g})")
assert err < 1e-9
X_h.x.array[:] = X.x.array                       # restore the initial state

# ---------------------------------------------------------------------------
# Output sampling on the IB2d grid
# ---------------------------------------------------------------------------
gx = np.arange(Nx) * (Lx / Nx)
gy = np.arange(Ny) * (Ly / Ny)
Vdof = Vc.tabulate_dof_coordinates()[:, :2]
iu = np.rint(Vdof[:, 0] / (Lx / Nx)).astype(int)
ju = np.rint(Vdof[:, 1] / (Ly / Ny)).astype(int)
on_grid = lambda P, i, j: (np.isclose(P[:, 0], i * (Lx / Nx))
                           & np.isclose(P[:, 1], j * (Ly / Ny)))
keep = (iu < Nx) & (ju < Ny) & on_grid(Vdof, iu, ju)
Q2s = fem.functionspace(mesh, ("Lagrange", 2))
p_grid_fn = fem.Function(Q2s)
Pdof = Q2s.tabulate_dof_coordinates()[:, :2]
ip = np.rint(Pdof[:, 0] / (Lx / Nx)).astype(int)
jp = np.rint(Pdof[:, 1] / (Ly / Ny)).astype(int)
keep_p = (ip < Nx) & (jp < Ny) & on_grid(Pdof, ip, jp)


def grid_fields():
    u = np.zeros((Ny, Nx, 2))
    u[ju[keep], iu[keep]] = solver.u_.x.array.reshape(-1, 2)[keep]
    p_grid_fn.interpolate(solver.p_)
    p = np.zeros((Ny, Nx))
    p[jp[keep_p], ip[keep_p]] = p_grid_fn.x.array[keep_p]
    return u, p


V1 = fem.functionspace(mesh, basix.ufl.element("Lagrange", "quadrilateral", 1, shape=(2,)))
u_io, f_io = fem.Function(V1, name="u"), fem.Function(V1, name="f")
p_io = fem.Function(fem.functionspace(mesh, ("Lagrange", 1)), name="p")
xf = dolfinx.io.XDMFFile(comm, os.path.join(out_dir, "fluid.xdmf"), "w")
xs = dolfinx.io.XDMFFile(comm, os.path.join(out_dir, "structure.xdmf"), "w")
xf.write_mesh(mesh)
xs.write_mesh(structure)
disp = fem.Function(Vs, name="displacement")
X0 = X.x.array.copy()


def write_output(t):
    u_io.interpolate(solver.u_)
    f_io.interpolate(solver.f)
    p_io.interpolate(solver.p_)
    for fn in (u_io, p_io, f_io):
        xf.write_function(fn, t)
    disp.x.array[:] = X.x.array - X0
    xs.write_function(disp, t)


hist = {"t": [0.0], "X": [marker_array(X).copy()], "com": [], "apex": []}
u0, p0 = grid_fields()
hist["u"], hist["p"] = [u0], [p0]


def bell_metrics():
    Xm = marker_array(X)
    com = Xm[:n_bell].mean(axis=0)
    return com, Xm[0].copy()


hist["com"].append(bell_metrics()[0])
hist["apex"].append(bell_metrics()[1])
write_output(0.0)

# ---------------------------------------------------------------------------
# Time loop — Peskin (2002) / IB2d IBM_Driver ordering
# ---------------------------------------------------------------------------
tic = time.perf_counter()
for step in range(num_steps):
    # (1) half-step Lagrangian positions X_h = X + dt/2 U^n(X)
    ib.evaluate_current_points(X._cpp_object)
    if step == 0:
        X_h.x.array[:] = X.x.array           # u = 0 initially (as IB2d)
    else:
        ib.fluid_to_solid(ib_velocity(solver.u_n)._cpp_object, U_s._cpp_object)
        X_h.x.array[:] = X.x.array + 0.5 * dt * U_s.x.array

    # (1b) muscle drive: resting lengths at the *start* time of the step
    #      (IBM_Driver calls update_Springs(dt, current_time, ...) before the
    #      force evaluation, with current_time = step * dt)
    if UPDATE_SPRINGS:
        update_muscles(step * dt)

    # (2) spring + beam + target forces at X_h, spread with the 4-point kernel
    spread_forces_at_half()

    # (3) two-stage fluid solve: u_h, u^{n+1}, p^{n+1/2}
    solver.solve_one_step()

    # (4) X^{n+1} = X^n + dt U_h(X_h)
    ib.fluid_to_solid(ib_velocity(solver.u_h)._cpp_object, U_s._cpp_object)
    X.x.array[:] += dt * U_s.x.array
    X.x.scatter_forward()

    t = (step + 1) * dt
    if (step + 1) % print_dump == 0 or step + 1 == num_steps:
        Xm = marker_array(X).copy()
        com, apex = bell_metrics()
        hist["t"].append(t)
        hist["X"].append(Xm)
        hist["com"].append(com)
        hist["apex"].append(apex)
        ug, pg = grid_fields()
        hist["u"].append(ug)
        hist["p"].append(pg)
        write_output(t)
        if comm.rank == 0:
            print(f"step {step+1:6d}  t={t:.4f}  com_y={com[1]:.5f}  "
                  f"apex_y={apex[1]:.5f}  max|u|={np.abs(solver.u_.x.array).max():.4e}  "
                  f"wall={time.perf_counter()-tic:.1f}s", flush=True)

xf.close()
xs.close()
np.savez_compressed(os.path.join(out_dir, f"afsi_result_g{GRAD_DIV:g}.npz"),
                    t=np.array(hist["t"]), X=np.array(hist["X"]),
                    u=np.array(hist["u"]), p=np.array(hist["p"]),
                    com=np.array(hist["com"]), apex=np.array(hist["apex"]),
                    n_bell=n_bell, dx=Lx / Nx, dy=Ly / Ny)
if comm.rank == 0:
    print(f"done in {time.perf_counter()-tic:.1f}s -> "
          f"{out_dir}/afsi_result_g{GRAD_DIV:g}.npz")
