"""Python port of IB2d's ``Make_Jelly_Geometry.m`` (+ ``input2d`` writer).

    python make_jelly.py <out_dir> [Ny] [dt] [Tfinal] [print_dump]

Writes ``input2d``, ``jelly.vertex``, ``jelly.spring``, ``jelly.target`` and
``jelly.nonInv_beam`` for the Hoover-Jellyfish model (Battista's IB2d port of
Hoover & Miller 2015, "A numerical study of the benefits of driving jellyfish
bells at their natural frequency", J. Theor. Biol. 374) on an Nx x Ny grid with
Nx = Ny * Lx / Ly (square cells).

Model ingredients (identical to ``Make_Jelly_Geometry.m``):

* Lagrangian spacing ``ds = min(Lx/(2 Nx), Ly/(2 Ny))`` (= dx/2);
* the bell is the ellipse x = a cos t, y = b sin t with a = 0.5, b = 0.75,
  truncated at y = d = -0.25 (theta_lim = asin(d/b)), shifted to (1.5, 2.0);
  npts = 2*npts_wing - 1 points along the bell outline (apex first, then the
  left side, then the right side);
* springs: 2*npts_wing structural springs (the bell outline, stiffness
  kappa_spring = 1e7 written as kappa_spring/ds in the file -- the file value
  is what IB2d simulates) plus npts_musc = floor(npts_wing/4) *muscle* springs
  of stiffness F = 1e5 connecting the two arm tips; the muscles are written as
  the LAST rows of the .spring file (this order is depended upon by the muscle
  driver of ``run_reference.py`` and by main.py);
* non-invariant beams (stiffness kappa_beam = 2.5e5 written as
  kappa_beam/ds^3) along the bell outline; each beam stores the reference
  second difference (C1, C2) of its three points at t = 0;
* a line of ``flow blocker`` target points of stiffness k_Target = 2.5e6 at
  x = ds : 4 ds : Lx - ds, y = Ly - 4 ds, tethered to their initial positions.
"""
import os
import sys

import numpy as np

A_SEMI = 0.5          # bell semi-axis in x
B_SEMI = 0.75         # bell semi-axis in y
Y_LOW = -0.25         # lowest point along the bell
KAPPA_SPRING = 1e7    # spring constant (N)
KAPPA_BEAM = 2.5e5    # beam stiffness (N m^2)
F_MUSCLE = 1e5        # jellyfish contraction force
K_TARGET = 2.5e6      # target (blocker) stiffness

INPUT2D_TEMPLATE = """\
%*****%***%***%***%***%***% INPUT2d FILE: %***%***%***%***%***%*****%
% HOOVER JELLYFISH (IB2d Example_Jellyfish_Swimming/Hoover_Jellyfish)
% generated by afsic/demo/ib2d/demo_445/make_jelly.py

Fluid_Parameters {{
mu = {mu}            % Dynamic Viscosity (N*s/m^2)
rho = {rho}            % Density (kg/m^3)
}}

Temporal_Information {{
Tfinal = {Tfinal}         % Final time of simulation (s)
dt = {dt}          % Time-step (s)
}}

Grid_Parameters {{
Nx =  {Nx}               % # of Eulerian Grid Pts. in x-Direction (MUST BE EVEN!!!)
Ny =  {Ny}               % # of Eulerian Grid Pts. in y-Direction (MUST BE EVEN!!!)
Lx = {Lx}                % Length of Eulerian Grid in x-Direction (m)
Ly = {Ly}                % Length of Eulerian Grid in y-Direction (m)
supp = 4                % Choose dirac-delta support (KEEP IT EVEN!!!)
}}

Lag_Structure_Info {{
springs = 1             % 0 (for no) or 1 (for yes)
update_springs = 1      % 0 (for no) or 1 (for yes)
target_pts = 1          % 0 (for no) or 1 (for yes)
update_target = 0       % 0 (for no) or 1 (for yes)
beams = 0               % 0 (for no) or 1 (for yes) % "Torsional Springs"
update_beams = 0        % 0 (for no) or 1 (for yes) % Update "Torsional Springs"
nonInvariant_beams = 1  % 0 (for no) or 1 (for yes) % "non-Invariant Beams"
update_nonInv_beams = 0 % 0 (for no) or 1 (for yes) % Update "non-Invariant Beams"
FV_LT_muscle = 0        % 0 (for no) or 1 (for yes) % Force-Velocity & Length-Tension Model
3_element_muscle = 0    % 0 (for no) or 1 (for yes) % Hill 3-Element Model w/ Force-Velocity & Length-Tension Model
arb_ext_force = 0       % 0 (for no) or 1 (for yes)
tracers = 0             % 0 (for no) or 1 (for yes)
mass_pts = 0            % 0 (for no) or 1 (for yes)
gravity = 0             % 0 (for no) or 1 (for yes) %PLEASE CHECK GRAVITY VECTOR BELOW
x_gravity_vec_comp = 0  % x-Component of Gravity Vector
y_gravity_vec_comp = -1 % y-Component of Gravity Vector
porous_media = 0        % 0 (for no) or 1 (for yes)
electro_phys = 0        % 0 (for no) or 1 (for yes)
damped_springs = 0      % 0 (for no) or 1 (for yes)
update_damp_springs = 0 % 0 (for no) or 1 (for yes)
boussinesq = 0          % 0 (for no) or 1 (for yes)  % FOR BOUSSINESQ APPROXIMATION!
expansion_coeff = 1.0   % expansion coefficient for Boussinesq approx.
user_force_model = 0    % 0 (for no) or 1 (for yes)
}}

Output_Info {{
print_dump = {print_dump}       % How often to print (PLOT) to screen
save_Vorticity = 1       % Save Vorticity Scalar Data to .vtk format
save_Pressure = 1        % Save Pressure Scalar Data to .vtk format
save_uVec = 1            % Save u-Vector Data to .vtk format
save_uMag = 0            % Save uMagnitude Scalar Data to .vtk format
save_uX = 0              % Save uX Scalar Data to .vtk format
save_uY = 0              % Save uY Scalar Data to .vtk format
save_fMag = 0            % Save Force Magnitude Scalar Data to .vtk format
save_fX = 0              % Save x-Force Component Scalar Data to .vtk format
save_fY = 0              % Save y-Force Component Scalar Data to .vtk format
save_hier = 0            % Save Scalar Force Data on Lag. Structure to .vtk format
plot_Matlab = 0          % Plot in Matlab? (1=YES, 0=NO)
plot_LagPts = 1          % Plot Lagrangian Points ONLY in Matlab
plot_Velocity = 1        % Plot Lagrangian Points + VELOCITY FIELD in Matlab
plot_Vorticity = 1       % Plot Lagrangian Points + VORTICITY colormap in Matlab
plot_MagVelocity = 1     % Plot Lagrangian Points + MAGNITUDE OF VELOCITY colormap in Matlab
plot_Pressure = 1        % Plot Lagrangian Points + PRESSURE colormap in Matlab
}}

Lag_Name {{
string_name = "jelly"  % String name for simulation
}}
"""


def build(Ny, Lx=3.0, Ly=10.0, mu=6.667, rho=1000.0):
    """Return the vertex/spring/target/beam arrays for the Hoover jellyfish."""
    Nx = int(round(Ny * Lx / Ly))
    ds = min(Lx / (2 * Nx), Ly / (2 * Ny))

    # --- bell outline (apex first, then left side, then right side) ---------
    theta_lim = np.arcsin(Y_LOW / B_SEMI)
    theta = np.pi / 2
    xl, yl = [], []
    while theta < np.pi - theta_lim:
        xl.append(A_SEMI * np.cos(theta))
        yl.append(B_SEMI * np.sin(theta))
        theta += ds / np.sqrt((A_SEMI * np.sin(theta)) ** 2
                              + (B_SEMI * np.cos(theta)) ** 2)
    xl, yl = np.array(xl), np.array(yl)
    n_wing = len(xl) - 1
    npts = 2 * n_wing + 1
    x = np.concatenate([xl, -xl[1:]]) + 1.5
    y = np.concatenate([yl, yl[1:]]) + 2.0
    n_musc = n_wing // 4                       # floor(npts_wing/4)

    # --- flow blocker line along the top edge ------------------------------
    n_blk = int(np.floor((Lx - ds - ds) / (4 * ds))) + 1
    xb = ds + 4 * ds * np.arange(n_blk)
    yb = np.full(n_blk, Ly - 4 * ds)
    X = np.vstack([np.column_stack([x, y]), np.column_stack([xb, yb])])
    Nb = len(X)

    def dist(a, b):                            # 1-based indices, as in the .m
        return float(np.sqrt((X[a - 1, 0] - X[b - 1, 0]) ** 2
                             + (X[a - 1, 1] - X[b - 1, 1]) ** 2))

    # --- springs: left side, right side, then the muscles ------------------
    m1, m2, ks, L0 = [], [], [], []
    k_edge = KAPPA_SPRING / ds
    for s in range(1, n_wing + 1):             # left side: (s, s+1)
        m1.append(s); m2.append(s + 1); ks.append(k_edge); L0.append(dist(s, s + 1))
    for s in range(1, n_wing + 1):             # right side
        if s == 1:
            a, b = 1, n_wing + 2
        else:
            a, b = (s - 1) + (n_wing + 1), s + (n_wing + 1)
        m1.append(a); m2.append(b); ks.append(k_edge); L0.append(dist(a, b))
    ind_l = 1 + n_wing - n_musc + 1            # first muscle point on the left arm
    ind_r = 1 + 2 * n_wing - n_musc + 1        # first muscle point on the right arm
    for s in range(n_musc):                    # muscles between the arm tips
        a, b = ind_l + s, ind_r + s
        m1.append(a); m2.append(b); ks.append(F_MUSCLE); L0.append(dist(a, b))
    springs = dict(p1=np.array(m1, np.int64) - 1, p2=np.array(m2, np.int64) - 1,
                   k=np.array(ks), L0=np.array(L0), n_musc=n_musc, n_wing=n_wing)

    # --- non-invariant beams (reference second differences) ----------------
    b1, b2, b3, bk, C = [], [], [], [], []
    kb = KAPPA_BEAM / ds ** 3

    def beam(i1, i2, i3):
        b1.append(i1); b2.append(i2); b3.append(i3); bk.append(kb)
        C.append([X[i1 - 1, 0] + X[i3 - 1, 0] - 2 * X[i2 - 1, 0],
                  X[i1 - 1, 1] + X[i3 - 1, 1] - 2 * X[i2 - 1, 1]])

    beam(2, 1, n_wing + 2)                     # middle three points at the top
    for s in range(2, n_wing + 1):             # left side
        beam(s + 1, s, s - 1)
    for s in range(2, n_wing + 1):             # right side
        ss = s + n_wing
        if s == 2:
            beam(1, ss, ss + 1)
        else:
            beam(ss - 1, ss, ss + 1)
    beams = dict(p1=np.array(b1, np.int64) - 1, p2=np.array(b2, np.int64) - 1,
                 p3=np.array(b3, np.int64) - 1, kb=np.array(bk),
                 C=np.array(C))

    # --- blockers as target points -----------------------------------------
    tgt = dict(ids=np.arange(npts, Nb, dtype=np.int64), k=np.full(Nb - npts, K_TARGET))
    return dict(Nx=Nx, Ny=Ny, Lx=Lx, Ly=Ly, ds=ds, X=X, springs=springs,
                beams=beams, targets=tgt, npts=npts, n_wing=n_wing, n_musc=n_musc,
                mu=mu, rho=rho)


def write(out, Ny, dt, Tfinal, print_dump, Lx=3.0, Ly=10.0, mu=6.667, rho=1000.0):
    g = build(Ny, Lx, Ly, mu, rho)
    os.makedirs(out, exist_ok=True)
    Nx, ds, X = g["Nx"], g["ds"], g["X"]

    with open(os.path.join(out, "jelly.vertex"), "w") as fh:
        fh.write(f"{len(X)}\n")
        for xv, yv in X:
            fh.write(f"{xv:1.16e} {yv:1.16e}\n")

    sp = g["springs"]
    with open(os.path.join(out, "jelly.spring"), "w") as fh:
        fh.write(f"{len(sp['p1'])}\n")
        for a, b, k, L in zip(sp["p1"] + 1, sp["p2"] + 1, sp["k"], sp["L0"]):
            fh.write(f"{a} {b} {k:1.16e} {L:1.16e} 1\n")

    bm = g["beams"]
    with open(os.path.join(out, "jelly.nonInv_beam"), "w") as fh:
        fh.write(f"{len(bm['p1'])}\n")
        for a, b, c, k, C in zip(bm["p1"] + 1, bm["p2"] + 1, bm["p3"] + 1,
                                 bm["kb"], bm["C"]):
            fh.write(f"{a} {b} {c} {k:1.16e} {C[0]:1.16e} {C[1]:1.16e}\n")

    tg = g["targets"]
    with open(os.path.join(out, "jelly.target"), "w") as fh:
        fh.write(f"{len(tg['ids'])}\n")
        for i, k in zip(tg["ids"] + 1, tg["k"]):
            fh.write(f"{i} {k:1.16e}\n")

    with open(os.path.join(out, "input2d"), "w") as fh:
        fh.write(INPUT2D_TEMPLATE.format(
            Nx=Nx, Ny=Ny, Lx=f"{Lx:.1f}", Ly=f"{Ly:.1f}", mu=mu, rho=rho,
            dt=f"{dt:.1e}", Tfinal=f"{Tfinal:.1f}", print_dump=print_dump))

    print(f"wrote {out}: Nx={Nx} Ny={Ny} ds={ds:g} "
          f"bell={g['npts']} pts ({g['n_wing']} per side), "
          f"muscles={g['n_musc']}, springs={len(sp['p1'])}, "
          f"beams={len(bm['p1'])}, blockers={len(tg['ids'])}, "
          f"dt={dt:g}, Tfinal={Tfinal}, print_dump={print_dump}")
    return g


if __name__ == "__main__":
    args = sys.argv[1:]
    out = args[0]
    vals = list(args[1:]) + ["160", "4e-5", "1.0", "250"][len(args) - 1:]
    write(out, int(vals[0]), float(vals[1]), float(vals[2]), int(vals[3]))
