services:
  mapengfei_afsi_dev_gpu_1:
    image: mapengfei/dolfinx:local
    container_name: afsi_dev_gpu_1
    runtime: nvidia  # 关键：指定使用 nvidia 运行时
    command: tail -f /dev/null
    volumes:
      - ../..:/root
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # 关键：设置可见的 GPU
      - NVIDIA_DRIVER_CAPABILITIES=all
    shm_size: 8g
    mem_limit: 128g  # 直接使用 mem_limit 而不是 deploy.resources.limits